2017 optimizations
anton-malakhov/scipy_proceedings pull request #22
Opened 2017-06-21 20:46 UTC by oleksandr-pavlyk

Further edits. Fixed width of the jitted code in `parallel.rst`.

2017-06-21 21:55 UTC, oleksandr-pavlyk commented
@anton-malakhov  @DrTodd13

2017-06-21 22:25 UTC, anton-malakhov requested changes

2017-06-21 22:25 UTC, anton-malakhov commented on papers/oleksandr_pavlyk/parallel/parallel.rst
> +Auto-parallelization proves to be an effective optimization for these benchmarks, achieving speedups from 5.9x to 11.8x over sequential Numba on 12-core Xeon |R| X5680 @3.33GHz with 64GB RAM. The ben
`Intel |R| Xeon |R| X5680`

2017-06-22 03:41 UTC, anton-malakhov approved these changes

2017-06-22 10:42 UTC, merged